apiVersion: apps/v1
kind: Deployment
metadata:
  name: thewilliamkeel
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: thewilliamkeel
  template:
    metadata:
      labels:
        app: thewilliamkeel
    spec:
      containers:
      - name: thewilliamkeel
        image: thewilliamkeel:latest
        ports:
      - containerPort: 5000
    imagePullSecrets:
    - name: regcred
