apiVersion: apps/v1
kind: Deployment
metadata:
  name: thewilliamkeel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thewilliamkeel
  template:
    metadata:
      labels:
        app: thewilliamkeel
    spec:
      containers:
      - name: thewilliamkeel
        image: thewilliamkeel:latest
        ports:
        - containerPort: 5000
        livenessProbe: 
          httpGet:
            path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
    imagePullSecrets:
    - name: regcred
